//
//  OllamaKit+Chat.swift
//
//
//  Created by Kevin Hermawan on 02/01/24.
//

import Alamofire
import Combine
import Foundation

extension OllamaKit {
    /// Establishes an asynchronous stream for chat responses from the Ollama API, based on the provided data.
    ///
    /// This method sets up a streaming connection using Swift's concurrency features, allowing for real-time data handling as chat responses are generated by the Ollama API.
    ///
    /// ```swift
    /// let ollamaKit = OllamaKit()
    /// let chatData = OKChatRequestData(/* parameters */)
    ///
    /// Task {
    ///     do {
    ///         for try await response in ollamaKit.chat(data: chatData) {
    ///             // Handle each chat response
    ///         }
    ///     } catch {
    ///         // Handle error
    ///     }
    /// }
    /// ```
    ///
    /// - Parameter data: The ``OKChatRequestData`` used to initiate the chat streaming from the Ollama API.
    /// - Returns: An `AsyncThrowingStream<OKChatResponse, Error>` emitting the live stream of chat responses from the Ollama API.
    public func chat(data: OKChatRequestData) -> AsyncThrowingStream<OKChatResponse, Error> {
        AsyncThrowingStream { continuation in
            let request = AF.streamRequest(router.chat(data: data)).validate()
            var buffer = Data()
            
            request.responseStream { stream in
                switch stream.event {
                case .stream(let result):
                    switch result {
                    case .success(let data):
                        buffer.append(data)
                        
                        while let chunk = extractNextJSON(from: &buffer) {
                            do {
                                let response = try decoder.decode(OKChatResponse.self, from: chunk)
                                continuation.yield(response)
                            } catch {
                                continuation.finish(throwing: error)
                                return
                            }
                        }
                    case .failure(let error):
                        continuation.finish(throwing: error)
                    }
                case .complete(_):
                    continuation.finish()
                }
            }
        }
    }
    
    /// Establishes a Combine publisher for streaming chat responses from the Ollama API, based on the provided data.
    ///
    /// This method sets up a streaming connection using the Combine framework, facilitating real-time data handling as chat responses are generated by the Ollama API.
    ///
    /// ```swift
    /// let ollamaKit = OllamaKit()
    /// let chatData = OKChatRequestData(/* parameters */)
    ///
    /// ollamaKit.chat(data: chatData)
    ///     .sink(receiveCompletion: { completion in
    ///         // Handle completion or error
    ///     }, receiveValue: { chatResponse in
    ///         // Handle each chat response
    ///     })
    ///     .store(in: &cancellables)
    /// ```
    ///
    /// - Parameter data: The ``OKChatRequestData`` used to initiate the chat streaming from the Ollama API.
    /// - Returns: An `AnyPublisher<OKChatResponse, Error>` emitting the live stream of chat responses from the Ollama API.
    public func chat(data: OKChatRequestData) -> AnyPublisher<OKChatResponse, Error> {
        let subject = PassthroughSubject<OKChatResponse, Error>()
        let request = AF.streamRequest(router.chat(data: data)).validate()
        var buffer = Data()
        
        request.responseStream { stream in
            switch stream.event {
            case .stream(let result):
                switch result {
                case .success(let data):
                    buffer.append(data)
                    
                    while let chunk = extractNextJSON(from: &buffer) {
                        do {
                            let response = try decoder.decode(OKChatResponse.self, from: chunk)
                            subject.send(response)
                        } catch {
                            subject.send(completion: .failure(error))
                            return
                        }
                    }
                case .failure(let error):
                    subject.send(completion: .failure(error))
                }
            case .complete(_):
                subject.send(completion: .finished)
            }
        }
        
        return subject.eraseToAnyPublisher()
    }
}
