//
//  OllamaKit+Generate.swift
//
//
//  Created by Kevin Hermawan on 02/01/24.
//

import Alamofire
import Combine
import Foundation

extension OllamaKit {
    /// Establishes an asynchronous stream for responses from the Ollama API, based on the provided data.
    ///
    /// This method sets up a streaming connection using Swift's concurrency features, allowing for real-time data handling as the responses are generated by the Ollama API.
    ///
    /// ```swift
    /// let ollamaKit = OllamaKit()
    /// let requestData = OKGenerateRequestData(/* parameters */)
    ///
    /// Task {
    ///     do {
    ///         for try await response in ollamaKit.generate(data: requestData) {
    ///             // Handle each generated response
    ///         }
    ///     } catch {
    ///         // Handle error
    ///     }
    /// }
    /// ```
    ///
    /// - Parameter data: The ``OKGenerateRequestData`` used to initiate the streaming from the Ollama API.
    /// - Returns: An `AsyncThrowingStream<OKGenerateResponse, Error>` emitting the live stream of responses from the Ollama API.
    public func generate(data: OKGenerateRequestData) -> AsyncThrowingStream<OKGenerateResponse, Error> {
        AsyncThrowingStream { continuation in
            let request = AF.streamRequest(router.generate(data: data)).validate()
            
            request.responseStreamDecodable(of: OKGenerateResponse.self, using: decoder) { stream in
                switch stream.event {
                case .stream(let result):
                    switch result {
                    case .success(let response):
                        continuation.yield(response)
                    case .failure(let error):
                        continuation.finish(throwing: error)
                    }
                case .complete(let completion):
                    if let error = completion.error {
                        continuation.finish(throwing: error)
                    } else {
                        continuation.finish()
                    }
                }
            }
        }
    }
    
    /// Establishes a Combine publisher for streaming responses from the Ollama API, based on the provided data.
    ///
    /// This method sets up a streaming connection using the Combine framework, allowing for real-time data handling as the responses are generated by the Ollama API.
    ///
    /// ```swift
    /// let ollamaKit = OllamaKit()
    /// let requestData = OKGenerateRequestData(/* parameters */)
    ///
    /// ollamaKit.generate(data: requestData)
    ///     .sink(receiveCompletion: { completion in
    ///         // Handle completion or error
    ///     }, receiveValue: { generateResponse in
    ///         // Handle each generated response
    ///     })
    ///     .store(in: &cancellables)
    /// ```
    ///
    /// - Parameter data: The ``OKGenerateRequestData`` used to initiate the streaming from the Ollama API.
    /// - Returns: An `AnyPublisher<OKGenerateResponse, AFError>` emitting the live stream of responses from the Ollama API.
    public func generate(data: OKGenerateRequestData) -> AnyPublisher<OKGenerateResponse, AFError> {
        let subject = PassthroughSubject<OKGenerateResponse, AFError>()
        let request = AF.streamRequest(router.generate(data: data)).validate()
        
        request.responseStreamDecodable(of: OKGenerateResponse.self, using: decoder) { stream in
            switch stream.event {
            case .stream(let result):
                switch result {
                case .success(let response):
                    subject.send(response)
                case .failure(let error):
                    subject.send(completion: .failure(error))
                }
            case .complete(let completion):
                if completion.error != nil {
                    subject.send(completion: .failure(completion.error!))
                } else {
                    subject.send(completion: .finished)
                }
            }
        }
        
        return subject.eraseToAnyPublisher()
    }
}
